id = "mysql-context-server"
name = "MySQL Context Server"
description = "Model Context Server for MySQL"
version = "0.0.1"
schema_version = 1
authors = ["Zed Contributors"]
repository = "https://github.com/dahican/zed-mysql-context-server"

[context_servers.mysql-context-server]
name = "MySQL Context Server"
